<?php
/**
 * @var Rokanthemes\Newproduct\Block\Newproduct $block
 */
    $auto = $this->getConfig('auto');
	$speed = $this->getConfig('speed');
	$default = $this->getConfig('itemsDefault');
	$desktop = $this->getConfig('itemsDesktop');
	$desktop_small = $this->getConfig('itemsDesktopSmall');
	$tablet = $this->getConfig('itemsTablet');
	$mobile = $this->getConfig('itemsMobile');
	$show_next_back = $this->getConfig('next_back');
	$show_navigation_control = $this->getConfig('nav_ctrl');
	$showCompare = 1;
	$showWishlist = $this->getConfig('addtowishlist');
	$showCart = $this->getConfig('addtocart');

	use Magento\Framework\App\Action\Action;
	if($this->getConfig('enabled')){ // start enable module?>
		<?php $_productCollection = $this->getProducts();
	$_helper = $this->helper('Magento\Catalog\Helper\Output');
	$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;

?>

<div class="rokan-newproduct">
		<?php
			if ($block->getMode() == 'grid') {
				$viewMode = 'grid';
				$image = 'category_page_grid';
				// $showDescription = false;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			} else {
				$viewMode = 'list';
				$image = 'category_page_grid';
				// $showDescription = true;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
			}
			$pos = $block->getPositioned();

		?>
		<?php if($this->getConfig('title')){?>
			<div class="rokan-product-heading rokan-featured-heading"><h2><?php echo $this->getConfig('title')?></h2>
				<p class="description">
					<?php echo $this->getConfig('description')?>
				</p>
			</div>
		<?php }?>
		<?php if(!$_productCollection->getSize()): ?>
			<div class="rokan-newproduct-slider">
				<p class="note-msg"><?php echo __('There are no products matching the selection.') ?></p>
			</div>
		<?php else: ?>
			<?php
			$rows =  $this->getConfig('items_show');
			?>
			<div class="row">
				<ul id="new-product-slider" class="owl-carousel owl-theme">
					<?php $_collectionSize = $_productCollection->count() ?>
					<?php $i=0; foreach ($_productCollection as $_product): ?>
						<?php if($i %$rows == 0) echo "<li class='item newproductslider-item'>"; ?>

						<div class="product-item">
							<div class="item-inner">
								<?php
								$productImage = $block->getImage($_product, $image);
								if ($pos != null) {
									$position = ' style="left:' . $productImage->getWidth() . 'px;'
										. 'top:' . $productImage->getHeight() . 'px;"';
								}
								?>
								<?php // Product Image ?>
								<div class="product-photo">
									<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
										<?php $productImageThumb = $block->getImage($_product, 'category_page_grid-1');?>
										<span class="image0 image-switch">
											<?php echo $productImage->toHtml(); ?>
										</span>
										<span class="image1 image-switch">
											<?php echo $productImageThumb->toHtml(); ?>
										</span>
									</a>
									<div class="addto-links-icons visible-onhover">
										<div class="action-inner">
											<ul class="add-to-links">
											<?php if ($this->helper('Rokanthemes\QuickView\Helper\Data')->isEnable()){ ?>
												<li>
													<div class="quickview-product">
														<a href="javascript:void(0)" data-role="quickview-button" data-id="<?php echo $_product->getId(); ?>" data-href="<?php echo $block->getUrl('quickview/product/quickview/id/' . $_product->getId()) ?>" title="<?php echo $block->escapeHtml(__('Quick view')); ?>" class="ajax diamond tooltip-hover" data-placement="top" data-original-title="<?php echo ('Quick view') ?>"><i class="icon-eye1"></i></a>
												    </div>
												</li>
											<?php } ?>

											<?php if ($showCompare): ?>
											<?php
												$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
												?>
												<li><a href="#"
												   class="action button tocompare"
												   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
												   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
												   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
												   role="button">
													<i class="icon-stack"></i>
													</a>
												</li>
											<?php endif; ?>

											<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
												<li>
													<a href="#"
													   class="action button towishlist"
													   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
													   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
													   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
													   data-action="add-to-wishlist"
													   role="button">
														<i class="icon-heart"></i>
													</a>
												</li>
											<?php endif; ?>

											<?php if ($showCart): ?>
												<li>
													<div class="actions-add-cart">
														<div class="action-inner">
															<div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
																<?php if ($_product->isSaleable()): ?>
																	<?php $postParams = $block->getAddToCartPostParams($_product); ?>
																	<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
																		<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
																		<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
																		<?php echo $block->getBlockHtml('formkey')?>
																		<button type="submit"
																				title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
																				class="action tocart primary">
																			<i class="icon-shopping-bag"></i>
																		</button>
																	</form>
																<?php else: ?>
																	<?php if ($_product->getIsSalable()): ?>
																		<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
																	<?php else: ?>
																		<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
																	<?php endif; ?>
																<?php endif; ?>
															</div>

														</div>
													</div>
												</li>
												<?php endif; ?>
											</ul>
										</div>
									</div>

									<div class="product-label">
										<?php if ( $_product->getFinalPrice() < $_product->getPrice() ): ?>
											<span class="onsale">
												<span><?php echo __('Sale') ?></span>
											</span>
										<?php endif; ?>
									</div>
								</div>
								<div class="product-info">
									<?php
										$_productNameStripped = $block->stripTags($_product->getName(), null, true);
									?>
									<strong class="product-name">
										<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                            <?php
                                            $productName = $_helper->productAttribute($_product, $_product->getName(), 'name');
                                            $brandName = '';
                                            if (strpos($productName, '-') !== false) {
                                                $brandName = trim(substr($productName, 0, strpos($productName, '-')));
                                                $productName = trim(substr($productName, strpos($productName, '-') + 1));
                                            }
                                            ?>
                                            <div class="brand-name"><?= $brandName ?></div>
                                            <strong class="product name product-item-name">
                                                <a class="product-item-link"
                                                   href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                                    <?= /* @escapeNotVerified */ $productName ?>
                                                </a>
                                            </strong>
										</a>
									</strong>

                                    <div class="see-more-button">
                                        <a href="<?php echo $_product->getProductUrl() ?>" class="btn btn-secondary btn-filled">
                                            <?php echo __('See More') ?>
                                        </a>
                                    </div>

									<?php if ($templateType): ?>
										<?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?>
									<?php endif; ?>

									<?php if( $this->getConfig('show_price') ): ?>
										 <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
									<?php endif; ?>

								</div>
								<?php $i++;?>
							</div>
						</div>
						<?php if($i %$rows == 0) echo "</li>"; ?>
					<?php endforeach; ?>
						<?php if($i %$rows != 0) echo "</li>"; ?>
				</ul>
			</div>
		<?php if (!$block->isRedirectToCartEnabled()) : ?>
			<script type="text/x-magento-init">
			{
				"[data-role=tocart-form], .form.map.checkout": {
					"catalogAddToCart": {}
				}
			}
			</script>
		<?php endif; ?>
			<script>
				require([
					'jquery',
					'owlcarousel2'
				], function ($, owlCarousel) {
					$(function(){
						$(".rokan-newproduct #new-product-slider").owlCarousel({
							lazyLoad: true,
							center: true,
							loop:true,
							dots:false,
							nav:true,
							margin:30,
							navText: ["<i class='icon-chevron-left'></i>", "<i class='icon-chevron-right'></i>"],
							autoPlay :  <?php if($auto) echo 'true'; else echo 'false'; ?>,
							items : <?php echo $default; ?>,
							responsive:{
								<?php if($mobile){?>
								0:{
									items:<?php echo $mobile; ?>
								},
								<?php } if($mobile){?>
								479:{
									items:<?php echo $mobile; ?>
								},
								<?php }
								if($tablet){?>
								768:{
									items:<?php echo $tablet; ?>
								},
								<?php }
								if($desktop_small){?>
								991:{
									items:<?php echo $desktop_small; ?>
								},
								<?php }
								if($desktop){?>
								1199:{
									items:<?php echo $desktop; ?>
								}
								<?php }?>
							},
							slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
							paginationSpeed : 500,
							rewindSpeed : 500,
							navigation : <?php if($show_next_back) echo 'true'; else echo 'false'; ?>,
							stopOnHover : true,
							pagination :false,
							scrollPerPage:true,
						});
					});
				});
			</script>
	<?php endif; ?>
	</div>
<?php } ?>
