<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div class="block block-search pull-left switcher header_search" id="topsearch-dropdown">
    <!-- <span class="name" data-mage-init='{"dropdown":{}}' data-toggle="dropdown">
        <span class="action"><i class="fa fa-search"></i></span>
    </span> -->
    <div class="block block-content">
        <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
			<div class="form-group">
				<input id="search"
					   data-mage-init='{"quickSearch":{
							"formSelector":"#search_mini_form",
							"url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest'); ?>",
							"destinationSelector":"#search_autocomplete"}
					   }'
					   type="text"
					   name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
					   value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
					   placeholder="<?php /* @escapeNotVerified */ echo __('Search'); ?>"
					   class="input-text form-control top-search header_search-field"
					   maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
					   role="combobox"
					   aria-haspopup="false"
					   aria-autocomplete="both"
					   autocomplete="off"/>
				<button type="submit" title="<?php echo $block->escapeHtml(__('Search')) ?>" class="btn btn-primary">
					<!-- <em class="fa fa-search"></em> -->
          <span class="s-icon">Icon</span>
				</button>
				<div id="search_autocomplete" class="search-autocomplete"></div>
				<?php echo $block->getChildHtml() ?>
			</div>
        </form>
    </div>
</div>
