<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
?>

<?php
$_itemCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$themeHelper = $this->helper('FIRSTSHOW\Mpanel\Helper\Data');
$themeSettings = $themeHelper->getThemeSettings();
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())):?>
<?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'category_page_grid';
	  $imageTwo = 'category_page_two_grid';
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $cssClass = $block->getCss() ? __($block->getCss()) : '';
    $items = $block->getProductCollection()->getItems();
    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    //$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
    $per_row = 5; //$themeSettings['catalog']['per_row'];
    $size = $themeHelper->getImageSize();
    // var_dump($size);

?>
    <div class="block widget block-products-list <?php /* @escapeNotVerified */ echo $mode.' '.$cssClass; ?>">
        <?php if ($title):?>
        <div class="block-title col-md-12 col-sm-12 col-xs-12">
            <h3><?php /* @escapeNotVerified */ echo $title; ?></h3>
        </div>
        <?php endif ?>
        <div class="block-content col-md-12 col-sm-12 col-xs-12">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="row products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                <ol class="product-items <?php /* @escapeNotVerified */ echo $type; ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                      <?php

                        $ptype = $_item->getTypeId();
                        $actualId = $_item->getSku();
                        $childSelectAttrId = "";
                        // $IsOnlySimple = true;
                        if ($ptype == 'simple') {
                          $colorObj = $_item->getResource()->getAttribute('color');
                          $colorAttrId = $colorObj->getId();
                          $optionLabel = $colorObj->getFrontend()->getValue($_item);
                          if ($colorObj->usesSource()) {
                            $childAttrId = $colorObj->getSource()->getOptionId($optionLabel);
                            $childSelectAttrId = "option-label-color-$colorAttrId-item-$childAttrId";
                          }

                          $_helperParent = $this->helper('Twl\AdaptiveResize\Helper\Data');
                          $parentProductId = $_helperParent->getParentId($_item->getId());
                          if ($parentProductId) {
                            $_item = $_helperParent->getLoadProduct($parentProductId);
                            $ptype = $_item->getTypeId();
                            // $IsOnlySimple = false;
                          }
                          // var_dump($parentProductId);
                        }

                        $_helperGallery = $this->helper('Twl\AdaptiveResize\Helper\Gallery');
                        $_helperGallery->addGallery($_item);
                        $_helperGallery->setWidthHeight($size['width'], $size['height']);
                        $imagesUrls = $_helperGallery->getGalleryImages($_item);
                        // var_dump($imagesUrls);
                      ?>
                        <?php /* @escapeNotVerified */ //echo($iterator++ == 1) ? '<li class="item product product-item '. $themeHelper->getColClass($per_row) .'">' : '</li><li class="item product product-item '. $themeHelper->getColClass($per_row) .'">' ?>
                        <?php /* @escapeNotVerified */ //echo($iterator++ == 1) ? '<li class="item product product-item ">' : '</li><li class="item product product-item ">' ?>
						<?php
							$_itemNameStripped = $block->stripTags($_item->getName(), null, true);
              $productUrl = $block->getProductUrl($_item);
						?>
        <li class="item product product-item ">
        <div class="product-item-info product-content">
              <div class="product-top image-container-items only-<?php echo $ptype;?>-product" product_url="<?php /* @escapeNotVerified */ echo $productUrl; ?>"  title="<?php echo $_itemNameStripped ?>">

                <?php if ($imagesUrls) {

                  foreach ($imagesUrls as $img) {
                    ?>
                    <div class="product-image-item">
      								<a href="<?php /* @escapeNotVerified */ echo $productUrl; ?>" class="product-item-photo">
      									<img src="<?php echo $img; ?>" alt="<?php echo $_itemNameStripped ?>" class="img-responsive product-image-photo img-thumbnail"/>
      								</a>
      							</div>
                    <?php
                  }
                } ?>
              </div>
              <div class="product-item-details details product-desc">
                <?php
                  $new_product = $_item->getData('new_product');
                  if ($new_product == "1") {
                    echo '<div class="new-product-title"><span class="badge new_product">'.__('New').'</span></div>';
                  }
                  // echo $themeHelper->getProductLabel($_item);

                 ?>
                 <div class="home-page-pname-p_price">
                   <p class="product name product-item-name" >
                       <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                          href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                          class="product-item-link">
                           <?php echo $block->escapeHtml($_item->getName()) ?>
                       </a>
                   </p>
                   <?php echo $block->getProductPriceHtml($_item, $type); ?>
                 </div>

								<div class="desc-prd">
									<div class="information-prd child_selected_id" child_selected_id="<?php echo $childSelectAttrId; ?>">
										<?php //echo $block->getProductPriceHtml($_item, $type); ?>
                    <div class="pro-options-featured"><?php echo $block->getProductDetailsHtml($_item) ?></div>
									</div>
									<?php if ($showCart): ?>
										<div class="add-cart-item">
                      <div class="show-price-onhover">
                        <?php echo $block->getProductPriceHtml($_item, $type); ?>
                      </div>

											<div class="product-item-actions btn-add-to-bag">
												<?php if ($showCart): ?>
													<div class="actions-primary btn-add-to-bag">
                            <button class="action tocart primary btn btn-primary add-to-bag"
                                data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"}}'
                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Bag') ?>">
                              <span><?php /* @escapeNotVerified */ echo __('Add to Bag') ?></span>
                            </button>
														<?php if ($_item->isSaleable()): ?>
															<?php //if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
																<!-- <button class="action tocart primary btn btn-primary add-to-bag"
																		data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ //echo $block->getAddToCartUrl($_item) ?>"}}'
																		type="button" title="<?php /* @escapeNotVerified */ //echo __('Add to Bag') ?>">
																	<span><?php /* @escapeNotVerified */ //echo __('Add to Bag') ?></span>
																</button> -->
															<?php //else: ?>
																<?php
																	// $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
																	// $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
																?>
																<!-- <button class="action tocart primary btn btn-primary add-to-bag"
																		data-post='<?php /* @escapeNotVerified */ //echo $postData; ?>'
																		type="button" title="<?php /* @escapeNotVerified */ //echo __('Add to Bag') ?>">
																	<span> -->
                                    <!-- <span class="fa fa-shopping-cart"></span> -->
                                    <?php /* @escapeNotVerified */ //echo __('Add to Bag') ?></span>
																<!-- </button> -->
															<?php //endif; ?>

														<?php else: ?>
															<?php if ($_item->getIsSalable()): ?>
																<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
															<?php else: ?>
																<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
															<?php endif; ?>
														<?php endif; ?>
													</div>
												<?php endif; ?>
											</div>
										</div>
									<?php endif; ?>
								</div>
                            </div>
                        </div>
                      </li>
                        <?php //echo($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>
    <script type="text/javascript">
  		require([
  			'jquery',
  			'firstshow/owlcarousel'
  		], function(jQuery){
  			(function($) {
          // window.setInterval(function () {
          //   console.log('window.gridImageCarouselLoaded' + window.gridImageCarouselLoaded);
          // }, 500);
          var outerCarousel = $(".widget-product-grid");
  				outerCarousel.owlCarousel({
  					items: 5,
  					loop: true,
  					nav: true,
  					dots: true,
            pagination: false,
  					autoplayTimeout: 6000,
  					navText: ["<i class='fa fa-angle-left'	></i>","<i class='fa fa-angle-right'></i>"],
  					autoplay: false,
  					responsive:{
  						0 : {items: 1},
  						480 : {items: 1},
  						768 : {items: 3},
  						980 : {items: 4},
  						1200 : {items: 5}
  					}
  				});
          $(outerCarousel).unbind('change.owl.carousel');

          var innerOwlCarousel = $(".image-container-items.only-simple-product, .image-container-items.only-virtual-product").owlCarousel({
            items: 1,
            loop: false,
            nav: true,
            dots: false,
            pagination: false,
            autoplayTimeout: 6000,
            navText: ["<i class='fa fa-angle-left'	></i>","<i class='fa fa-angle-right'></i>"],
            autoplay: false,
            // responsive:{
            // 	0 : {items: 1},
            // 	480 : {items: 1},
            // 	768 : {items: 3},
            // 	980 : {items: 4},
            // 	1200 : {items: 5}
            // }
          });
          // $(innerOwlCarousel).unbind('change.owl.carousel');
          // $(".swatch-attribute-options").owlCarousel({
  				// 	items: 3,
  				// 	loop: false,
  				// 	nav: true,
  				// 	dots: false,
          //   pagination: false,
  				// 	autoplayTimeout: 6000,
  				// 	navText: ["<i class='fa fa-angle-left'	></i>","<i class='fa fa-angle-right'></i>"],
  				// 	autoplay: false,
  				// 	// responsive:{
  				// 	// 	0 : {items: 1},
  				// 	// 	480 : {items: 1},
  				// 	// 	768 : {items: 3},
  				// 	// 	980 : {items: 4},
  				// 	// 	1200 : {items: 5}
  				// 	// }
  				// });

  			})(jQuery);
  		});
  	</script>
<?php endif;?>
