<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php
    $_helper    = $this->helper('Magento\Catalog\Helper\Output');
    $_category  = $block->getCurrentCategory();
    $_imgHtml   = '';
    $_imgHtml = '<div class="category-image without-bg"><h2>'.$block->escapeHtml($_category->getName()).'</h2></div>';
    $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    /* @escapeNotVerified */ echo $_imgHtml;
//    if ($_imgUrl = $_category->getImageUrl()) {
//        $_imgHtml = '<div class="category-image" style="background:url(' . $_imgUrl . ')"><h2>'.$block->escapeHtml($_category->getName()).'</h2></div>';
//        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
//        /* @escapeNotVerified */ echo $_imgHtml;
//    }else{
//        $_imgHtml = '<div class="category-image without-bg"><h2>'.$block->escapeHtml($_category->getName()).'</h2></div>';
//        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
//        /* @escapeNotVerified */ echo $_imgHtml;
//    }
?>
