<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * New Customer block template
 *
 * @var $block \Magento\Customer\Block\Form\Login\Info
 */
?>

<?php //if ($block->getRegistration()->isAllowed()): ?>

<div class="block block-new-customer">
    <div class="block-title">
        <span id="block-new-customer-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('New Customers') ?></span>
    </div>
    <div class="block-content" aria-labelledby="block-new-customer-heading">
        <p>
          <?php /* @escapeNotVerified */ echo __('Save your information to check out faster, save items to your wishlist, and view your purchase and return history.') ?>
          <br>
          <br>
          <?php /* @escapeNotVerified */ echo __('Note: Only orders that are placed after account creation will be reflected in your FIRSTSHOW account.') ?>

        </p>
        <div class="actions-toolbar">
            <div class="primary">
                <a href="<?php /* @escapeNotVerified */ echo $block->getCreateAccountUrl() ?>" class="action create primary btn btn-default btn-lg btn-outline-dark--hover"><span><?php /* @escapeNotVerified */ echo __('Create an Account') ?></span></a>
            </div>
        </div>
    </div>
</div>
<?php //endif; ?>
