<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block newsletter custom-common-links">
    <h2><?php /* @escapeNotVerified */ echo __('STAY INFORMED') ?></h2>
    <p><?php /* @escapeNotVerified */ echo __('Sign up for the newsletter and stay informed.') ?></p>
    <div class="title"><strong> <?php /* @escapeNotVerified */ echo __('Newsletter') ?></strong></div>
    <div class="content">
        <form class="form subscribe"
              novalidate
              action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
              method="post"
              data-mage-init='{"validation": {"errorClass": "mage-error"}}'
              id="newsletter-validate-detail">
            <div class="field newsletter">
                <div class="control">
                    <input name="email" type="email" id="newsletter"
                           placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email here') ?>..."
                           data-validate="{required:true, 'validate-email':true}"/>

                    <button class="button action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                        <span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
                    </button>

                </div>
            </div>

        </form>
    </div>
</div>
