<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Language switcher template
 */
?>
<?php
    // $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    // $storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
    // $currencyCode = $storeManager->getStore()->getCurrentCurrencyCode();
    // $currency = $objectManager->create('Magento\Directory\Model\CurrencyFactory')->create()->load();
    // $currencySymbol = $currency->getCurrencySymbol();
    // var_dump($currencySymbol);
    // exit;
?>


<?php if (count($block->getStores())>1): ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
<?php foreach ($block->getStores() as $_lang): ?>
                <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
                    <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>'>
                            <?= $block->escapeHtml(__($_lang->getName())) ?></a>
                <?php endif; ?>
            <?php endforeach; ?>
<?php endif; ?>
