<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Language switcher template
 */
?>
<?php
    // $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    // $storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
    // $currencyCode = $storeManager->getStore()->getCurrentCurrencyCode();
    // $currency = $objectManager->create('Magento\Directory\Model\CurrencyFactory')->create()->load();
    // $currencySymbol = $currency->getCurrencySymbol();
    // var_dump($currencySymbol);
    // exit;
?>


<?php if (count($block->getStores())>1): ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
<div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?= $block->escapeHtmlAttr($id) ?>">

    <div class="actions dropdown options switcher-options">
        <div class="action toggle switcher-trigger" id="switcher-language-trigger<?= $block->escapeHtmlAttr($id) ?>">
            <span class="view-<?php echo $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                <!-- <span><span class="hidden-sm hidden-xs"><?php //echo __('Language: ') ?></span><?php //echo $block->escapeHtml($block->getCurrentStoreCode()) ?></span> -->
            </span>
            <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?> lang">
                <span><?= $block->escapeHtml(__($block->getStoreName())) ?></span>
            </strong>
        </div>
        <ul class="dropdown switcher-dropdown" style="display:none;"
            data-mage-init='{"dropdownDialog":{
                "appendTo":"#switcher-language<?php /* @escapeNotVerified */ echo $id ?> > .options",
                "triggerTarget":"#switcher-language-trigger<?php /* @escapeNotVerified */ echo $id ?>",
                "closeOnMouseLeave": false,
                "triggerClass":"active",
                "parentClass":"active",
                "defaultDialogClass":"dropdown-menu cu-dropdown",
                "buttons":null}}'>
            <?php foreach ($block->getStores() as $_lang): ?>
                <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
                    <li class="view-<?php echo $block->escapeHtml($_lang->getCode()); ?> switcher-option">
                        <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>'>
                            <?php echo $block->escapeHtml($_lang->getName()) ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>
