
<div class="top-content-home">
	<?php /*
	<div class="section-element shop_by_categories">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('shop_by_categories')->toHtml();?>
		</div>
	</div>
	<div class="section-element categories_tab">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('categories_tab')->toHtml();?>
		</div>
	</div>
	*/?>
	<div class="shoppen-header">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('shoppen-header')->toHtml();?>
	</div>
	<div class="select-element shoppen-section">
		<div class="container">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('populair-products')->toHtml();?>
		</div>
		<div class="container">
			<div class="view-our-range">
				<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('view-our-range')->toHtml();?>
			</div>
			<?php //echo $block->getLayout()->createBlock('Rokanthemes\Newproduct\Block\Newproduct')->setTemplate('Rokanthemes_Newproduct::newproduct.phtml')->toHtml();?>
		</div>
	</div>
	<?php //echo $block->getLayout()->createBlock('Rokanthemes\PriceCountdown\Block\Pricecountdown')->setTemplate('Rokanthemes_PriceCountdown::pricecountdown.phtml')->toHtml();?>
	<div class="category-home-sofa">
        <img src="/pub/media/bs_theme/main.png" alt="Image description">
<!--		--><?php //echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('category_home_sofa')->toHtml();?>
	</div>
	<div class="select-element hoeslakens">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('Hoeslakens')->toHtml();?>
			<?php //echo $block->getLayout()->createBlock('Rokanthemes\Newproduct\Block\Newproduct')->setTemplate('Rokanthemes_Newproduct::newproduct.phtml')->toHtml();?>
		</div>
	</div>
	<?php /* <div class="select-element box-blog">
		<div class="container">
			<?php //echo $block->getLayout()->createBlock('Rokanthemes\Blog\Block\Sidebar\Recent')->setTemplate('Rokanthemes_Blog::sidebar/slider.phtml')->toHtml();?>
		</div>
	</div>
	<div class="section-brands">
		<div class="container">
			<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('brand-logo')->toHtml(); ?>
		</div>
	</div>
	<div class="Instagram_static">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('Instagram_static')->toHtml();?>
	</div>*/ ?>
</div>
